<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PhimSeeder extends Seeder
{
    public function run()
    {
        DB::table('phims')->delete();

        DB::table('phims')->insert([
            [
                'id' => 1,
                'ten_phim' => 'Avengers: Endgame',
                'mo_ta' => 'Trận chiến cuối cùng của các Avengers chống lại Thanos.',
                'dao_dien' => 'Anthony Russo, Joe Russo',
                'dien_vien' => 'Robert Downey Jr., Chris Evans, Chris Hemsworth',
                'thoi_luong' => 181,
                'nam_san_xuat' => 2019,
                'quoc_gia' => 'USA',
                'movie_url' => 'endgame.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-10-01 09:00:00',
                'ngay_khoi_chieu' => '2024-10-15',
            ],
            [
                'id' => 2,
                'ten_phim' => 'Titanic',
                'mo_ta' => 'Chuyện tình bi thương trên con tàu Titanic huyền thoại.',
                'dao_dien' => 'James Cameron',
                'dien_vien' => 'Leonardo DiCaprio, Kate Winslet',
                'thoi_luong' => 195,
                'nam_san_xuat' => 1997,
                'quoc_gia' => 'USA',
                'movie_url' => 'titanic.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=2e-eXJ6HgkQ',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-09-15 10:30:00',
                'ngay_khoi_chieu' => '2024-09-25',
            ],
            [
                'id' => 3,
                'ten_phim' => 'Avatar: The Way of Water',
                'mo_ta' => 'Jake Sully bảo vệ gia đình trước hiểm họa mới tại Pandora.',
                'dao_dien' => 'James Cameron',
                'dien_vien' => 'Sam Worthington, Zoe Saldaña',
                'thoi_luong' => 190,
                'nam_san_xuat' => 2022,
                'quoc_gia' => 'USA',
                'movie_url' => 'avatar2.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=d9MyW72ELq0',
                'trang_thai' => 1,
                'trang_thai_chieu' => 0,
                'ngay_tao' => '2024-11-20 14:15:00',
                'ngay_khoi_chieu' => '2024-12-10',
            ],
            [
                'id' => 4,
                'ten_phim' => 'John Wick: Chapter 4',
                'mo_ta' => 'John Wick đối đầu hội đồng tối cao trong trận chiến sinh tử.',
                'dao_dien' => 'Chad Stahelski',
                'dien_vien' => 'Keanu Reeves, Donnie Yen',
                'thoi_luong' => 169,
                'nam_san_xuat' => 2023,
                'quoc_gia' => 'USA',
                'movie_url' => 'johnwick4.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-10-05 11:20:00',
                'ngay_khoi_chieu' => '2024-10-20',
            ],
            [
                'id' => 5,
                'ten_phim' => 'The Dark Knight',
                'mo_ta' => 'Batman đối đầu Joker trong cuộc chiến bảo vệ Gotham.',
                'dao_dien' => 'Christopher Nolan',
                'dien_vien' => 'Christian Bale, Heath Ledger',
                'thoi_luong' => 152,
                'nam_san_xuat' => 2008,
                'quoc_gia' => 'USA',
                'movie_url' => 'thedarkknight.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-08-20 16:45:00',
                'ngay_khoi_chieu' => '2024-09-01',
            ],
            [
                'id' => 6,
                'ten_phim' => 'Spider-Man: No Way Home',
                'mo_ta' => 'Peter Parker đối mặt với đa vũ trụ và các phản diện từ tương lai.',
                'dao_dien' => 'Jon Watts',
                'dien_vien' => 'Tom Holland, Andrew Garfield, Tobey Maguire',
                'thoi_luong' => 148,
                'nam_san_xuat' => 2021,
                'quoc_gia' => 'USA',
                'movie_url' => 'spiderman_nwh.mp4',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEZvT70PFBtMJrgszV7sKsiMh52TvkmwrS_g&s',
                'trailer_url' => 'https://www.youtube.com/watch?v=JfVOs4VSpmA',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-09-10 13:30:00',
                'ngay_khoi_chieu' => '2024-09-18',
            ],
            [
                'id' => 7,
                'ten_phim' => 'Interstellar',
                'mo_ta' => 'Một nhóm phi hành gia khám phá vũ trụ nhằm cứu loài người.',
                'dao_dien' => 'Christopher Nolan',
                'dien_vien' => 'Matthew McConaughey, Anne Hathaway',
                'thoi_luong' => 169,
                'nam_san_xuat' => 2014,
                'quoc_gia' => 'USA',
                'movie_url' => 'interstellar.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
                'trang_thai' => 1,
                'trang_thai_chieu' => 0,
                'ngay_tao' => '2024-11-22 15:00:00',
                'ngay_khoi_chieu' => '2024-12-15',
            ],
            [
                'id' => 8,
                'ten_phim' => 'Joker',
                'mo_ta' => 'Nguồn gốc hình thành Joker – kẻ thù số 1 của Batman.',
                'dao_dien' => 'Todd Phillips',
                'dien_vien' => 'Joaquin Phoenix',
                'thoi_luong' => 122,
                'nam_san_xuat' => 2019,
                'quoc_gia' => 'USA',
                'movie_url' => 'joker.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-10-08 12:15:00',
                'ngay_khoi_chieu' => '2024-10-22',
            ],
            [
                'id' => 9,
                'ten_phim' => 'Fast & Furious 9',
                'mo_ta' => 'Dom Toretto đối đầu người em trai mất tích Jakob.',
                'dao_dien' => 'Justin Lin',
                'dien_vien' => 'Vin Diesel, John Cena',
                'thoi_luong' => 143,
                'nam_san_xuat' => 2021,
                'quoc_gia' => 'USA',
                'movie_url' => 'ff9.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=aSiDu3Ywi8E',
                'trang_thai' => 1,
                'trang_thai_chieu' => 0,
                'ngay_tao' => '2024-11-25 09:30:00',
                'ngay_khoi_chieu' => '2024-12-20',
            ],
            [
                'id' => 10,
                'ten_phim' => 'Hacksaw Ridge',
                'mo_ta' => 'Câu chuyện có thật về người lính cứu thương không dùng súng.',
                'dao_dien' => 'Mel Gibson',
                'dien_vien' => 'Andrew Garfield',
                'thoi_luong' => 139,
                'nam_san_xuat' => 2016,
                'quoc_gia' => 'USA',
                'movie_url' => 'hacksaw.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/jhWbYeUNOA5zAb6ufK6pXQFXqTX.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=s2-1hz1juBI',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-09-25 14:45:00',
                'ngay_khoi_chieu' => '2024-10-05',
            ],
            [
                'id' => 11,
                'ten_phim' => 'Inception',
                'mo_ta' => 'Một đạo chích xâm nhập giấc mơ để lấy cắp ký ức.',
                'dao_dien' => 'Christopher Nolan',
                'dien_vien' => 'Leonardo DiCaprio, Joseph Gordon-Levitt',
                'thoi_luong' => 148,
                'nam_san_xuat' => 2010,
                'quoc_gia' => 'USA',
                'movie_url' => 'inception.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=YoHD9XEInc0',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-08-15 11:00:00',
                'ngay_khoi_chieu' => '2024-08-30',
            ],
            [
                'id' => 12,
                'ten_phim' => 'Frozen II',
                'mo_ta' => 'Anna và Elsa khám phá bí mật sức mạnh của Elsa.',
                'dao_dien' => 'Jennifer Lee, Chris Buck',
                'dien_vien' => 'Kristen Bell, Idina Menzel',
                'thoi_luong' => 103,
                'nam_san_xuat' => 2019,
                'quoc_gia' => 'USA',
                'movie_url' => 'frozen2.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/pjeMs3yqRmFL3giJy4PMXWZTTPa.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=bwzLiQZDw2I',
                'trang_thai' => 1,
                'trang_thai_chieu' => 0,
                'ngay_tao' => '2024-11-10 16:20:00',
                'ngay_khoi_chieu' => '2024-12-05',
            ],
            [
                'id' => 13,
                'ten_phim' => 'Black Panther: Wakanda Forever',
                'mo_ta' => 'Wakanda đối đầu thế lực mới dưới lòng đại dương.',
                'dao_dien' => 'Ryan Coogler',
                'dien_vien' => 'Letitia Wright, Tenoch Huerta',
                'thoi_luong' => 161,
                'nam_san_xuat' => 2022,
                'quoc_gia' => 'USA',
                'movie_url' => 'wakanda.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/ps2oKfhY6DL3alynlSqY97gHSsg.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=gV7vByGWX9o',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-10-12 08:45:00',
                'ngay_khoi_chieu' => '2024-10-28',
            ],
            [
                'id' => 14,
                'ten_phim' => 'The Batman',
                'mo_ta' => 'Batman đối đầu The Riddler trong cuộc điều tra bí ẩn.',
                'dao_dien' => 'Matt Reeves',
                'dien_vien' => 'Robert Pattinson, Zoë Kravitz',
                'thoi_luong' => 176,
                'nam_san_xuat' => 2022,
                'quoc_gia' => 'USA',
                'movie_url' => 'thebatman.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/74xTEgt7R36Fpooo50r9T25onhq.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=mqqft2x_Aa4',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-09-05 15:30:00',
                'ngay_khoi_chieu' => '2024-09-20',
            ],
            [
                'id' => 15,
                'ten_phim' => 'Venom: Let There Be Carnage',
                'mo_ta' => 'Venom đối đầu Carnage – một symbiote cực kỳ nguy hiểm.',
                'dao_dien' => 'Andy Serkis',
                'dien_vien' => 'Tom Hardy, Woody Harrelson',
                'thoi_luong' => 97,
                'nam_san_xuat' => 2021,
                'quoc_gia' => 'USA',
                'movie_url' => 'venom2.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/y2Ca1neKke2mGPMaHzlCNDVZqsK.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=-FmWuCgJmxo',
                'trang_thai' => 1,
                'trang_thai_chieu' => 0,
                'ngay_tao' => '2024-11-18 13:15:00',
                'ngay_khoi_chieu' => '2024-12-18',
            ],
            [
                'id' => 16,
                'ten_phim' => 'Doctor Strange in the Multiverse of Madness',
                'mo_ta' => 'Doctor Strange khám phá đa vũ trụ và đối đầu Wanda.',
                'dao_dien' => 'Sam Raimi',
                'dien_vien' => 'Benedict Cumberbatch, Elizabeth Olsen',
                'thoi_luong' => 126,
                'nam_san_xuat' => 2022,
                'quoc_gia' => 'USA',
                'movie_url' => 'drstrange2.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=aWzlQ2N6qqg',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-08-25 10:00:00',
                'ngay_khoi_chieu' => '2024-09-10',
            ],
            [
                'id' => 17,
                'ten_phim' => 'Guardians of the Galaxy Vol. 3',
                'mo_ta' => 'Star-Lord cùng đồng đội giải cứu Rocket.',
                'dao_dien' => 'James Gunn',
                'dien_vien' => 'Chris Pratt, Zoe Saldaña',
                'thoi_luong' => 150,
                'nam_san_xuat' => 2023,
                'quoc_gia' => 'USA',
                'movie_url' => 'gotg3.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=u3V5KDHRQvk',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-10-18 14:20:00',
                'ngay_khoi_chieu' => '2024-11-02',
            ],
            [
                'id' => 18,
                'ten_phim' => 'Deadpool 2',
                'mo_ta' => 'Deadpool lập đội X-Force để bảo vệ một cậu bé đột biến.',
                'dao_dien' => 'David Leitch',
                'dien_vien' => 'Ryan Reynolds, Josh Brolin',
                'thoi_luong' => 120,
                'nam_san_xuat' => 2018,
                'quoc_gia' => 'USA',
                'movie_url' => 'deadpool2.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=D86RtevtfrA',
                'trang_thai' => 1,
                'trang_thai_chieu' => 0,
                'ngay_tao' => '2024-12-01 11:40:00',
                'ngay_khoi_chieu' => '2024-12-25',
            ],
            [
                'id' => 19,
                'ten_phim' => 'The Lion King (Live Action)',
                'mo_ta' => 'Hành trình của Simba trên thảo nguyên châu Phi.',
                'dao_dien' => 'Jon Favreau',
                'dien_vien' => 'Donald Glover, Beyoncé',
                'thoi_luong' => 118,
                'nam_san_xuat' => 2019,
                'quoc_gia' => 'USA',
                'movie_url' => 'lionking.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=7TavVZMewpY',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-09-20 09:15:00',
                'ngay_khoi_chieu' => '2024-10-08',
            ],
            [
                'id' => 20,
                'ten_phim' => 'Dune',
                'mo_ta' => 'Paul Atreides bước vào cuộc chiến giành quyền lực tại hành tinh cát Arrakis.',
                'dao_dien' => 'Denis Villeneuve',
                'dien_vien' => 'Timothée Chalamet, Zendaya',
                'thoi_luong' => 155,
                'nam_san_xuat' => 2021,
                'quoc_gia' => 'USA',
                'movie_url' => 'dune.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=n9xhJrPXop4',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-10-25 16:00:00',
                'ngay_khoi_chieu' => '2024-11-10',
            ],
            [
                'id' => 21,
                'ten_phim' => 'Mission: Impossible – Dead Reckoning',
                'mo_ta' => 'Ethan Hunt đối đầu tổ chức The Entity nguy hiểm.',
                'dao_dien' => 'Christopher McQuarrie',
                'dien_vien' => 'Tom Cruise, Hayley Atwell',
                'thoi_luong' => 163,
                'nam_san_xuat' => 2023,
                'quoc_gia' => 'USA',
                'movie_url' => 'mi7.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/NNxYkU70HPurnNCSiCjYAmacwm.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=2m1drlOZSDw',
                'trang_thai' => 1,
                'trang_thai_chieu' => 0,
                'ngay_tao' => '2024-11-28 12:30:00',
                'ngay_khoi_chieu' => '2025-01-05',
            ],
            [
                'id' => 22,
                'ten_phim' => 'Transformers: Rise of the Beasts',
                'mo_ta' => 'Autobots hợp tác Maximals chống lại Unicron.',
                'dao_dien' => 'Steven Caple Jr.',
                'dien_vien' => 'Anthony Ramos, Dominique Fishback',
                'thoi_luong' => 127,
                'nam_san_xuat' => 2023,
                'quoc_gia' => 'USA',
                'movie_url' => 'transformers7.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/gPbM0MK8CP8A174rmUwGsADNYKD.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=itnqEauWQZM',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-10-30 10:45:00',
                'ngay_khoi_chieu' => '2024-11-15',
            ],
            [
                'id' => 23,
                'ten_phim' => 'The Marvels',
                'mo_ta' => 'Captain Marvel liên minh Kamala Khan và Monica Rambeau.',
                'dao_dien' => 'Nia DaCosta',
                'dien_vien' => 'Brie Larson, Iman Vellani',
                'thoi_luong' => 105,
                'nam_san_xuat' => 2023,
                'quoc_gia' => 'USA',
                'movie_url' => 'marvels.mp4',
                'poster_url' => 'https://www.elleman.vn/app/uploads/2023/11/14/227633/the-marvels-_elleman.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=wS_qbDztgVY',
                'trang_thai' => 1,
                'trang_thai_chieu' => 0,
                'ngay_tao' => '2024-12-05 14:10:00',
                'ngay_khoi_chieu' => '2025-01-12',
            ],
            [
                'id' => 24,
                'ten_phim' => 'Oppenheimer',
                'mo_ta' => 'Câu chuyện phát triển bom nguyên tử của J. Robert Oppenheimer.',
                'dao_dien' => 'Christopher Nolan',
                'dien_vien' => 'Cillian Murphy, Emily Blunt',
                'thoi_luong' => 180,
                'nam_san_xuat' => 2023,
                'quoc_gia' => 'USA',
                'movie_url' => 'oppenheimer.mp4',
                'poster_url' => 'https://m.media-amazon.com/images/M/MV5BM2RmYmVmMzctMzc5Ny00MmNiLTgxMGUtYjk1ZDRhYjA2YTU0XkEyXkFqcGc@._V1_.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=uYPbbksJxIg',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-08-10 13:25:00',
                'ngay_khoi_chieu' => '2024-08-25',
            ],
            [
                'id' => 25,
                'ten_phim' => 'Barbie',
                'mo_ta' => 'Barbie bước ra thế giới thật để khám phá bản thân.',
                'dao_dien' => 'Greta Gerwig',
                'dien_vien' => 'Margot Robbie, Ryan Gosling',
                'thoi_luong' => 114,
                'nam_san_xuat' => 2023,
                'quoc_gia' => 'USA',
                'movie_url' => 'barbie.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=pBk4NYhWNMM',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-11-05 15:50:00',
                'ngay_khoi_chieu' => '2024-11-20',
            ],
            [
                'id' => 26,
                'ten_phim' => 'Godzilla vs. Kong',
                'mo_ta' => 'Hai quái vật huyền thoại đối đầu nhau.',
                'dao_dien' => 'Adam Wingard',
                'dien_vien' => 'Millie Bobby Brown, Alexander Skarsgård',
                'thoi_luong' => 113,
                'nam_san_xuat' => 2021,
                'quoc_gia' => 'USA',
                'movie_url' => 'gvsk.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=odM92ap8_c0',
                'trang_thai' => 1,
                'trang_thai_chieu' => 0,
                'ngay_tao' => '2024-12-08 09:20:00',
                'ngay_khoi_chieu' => '2025-01-20',
            ],
            [
                'id' => 27,
                'ten_phim' => 'Aquaman and the Lost Kingdom',
                'mo_ta' => 'Aquaman đối đầu Black Manta mạnh hơn bao giờ hết.',
                'dao_dien' => 'James Wan',
                'dien_vien' => 'Jason Momoa, Patrick Wilson',
                'thoi_luong' => 124,
                'nam_san_xuat' => 2023,
                'quoc_gia' => 'USA',
                'movie_url' => 'aquaman2.mp4',
                'poster_url' => 'https://static.sweet.tv/images/cache/v3/movie_banner/CKjeARICZW4YAQ==/28456-aquaman-and-the-lost-kingdom_1280x720.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=UGc5Tzz19UY',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-11-12 11:35:00',
                'ngay_khoi_chieu' => '2024-11-25',
            ],
            [
                'id' => 28,
                'ten_phim' => 'The Flash',
                'mo_ta' => 'Barry Allen thay đổi dòng thời gian gây hỗn loạn đa vũ trụ.',
                'dao_dien' => 'Andy Muschietti',
                'dien_vien' => 'Ezra Miller, Michael Keaton',
                'thoi_luong' => 144,
                'nam_san_xuat' => 2023,
                'quoc_gia' => 'USA',
                'movie_url' => 'theflash.mp4',
                'poster_url' => 'https://media.posterstore.com/site_images/68631eb425436f8361d76899_1961150660_WB0143-5.jpg?auto=compress%2Cformat&fit=max&w=3840',
                'trailer_url' => 'https://www.youtube.com/watch?v=hebWYacbdvc',
                'trang_thai' => 1,
                'trang_thai_chieu' => 0,
                'ngay_tao' => '2024-12-12 16:45:00',
                'ngay_khoi_chieu' => '2025-01-28',
            ],
            [
                'id' => 29,
                'ten_phim' => 'The Matrix Resurrections',
                'mo_ta' => 'Neo quay trở lại Ma Trận trong hành trình mới.',
                'dao_dien' => 'Lana Wachowski',
                'dien_vien' => 'Keanu Reeves, Carrie-Anne Moss',
                'thoi_luong' => 148,
                'nam_san_xuat' => 2021,
                'quoc_gia' => 'USA',
                'movie_url' => 'matrix4.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/8c4a8kE7PizaGQQnditMmI1xbRp.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=9ix7TUGVYIo',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-11-08 12:00:00',
                'ngay_khoi_chieu' => '2024-11-22',
            ],
            [
                'id' => 30,
                'ten_phim' => 'The Hunger Games: The Ballad of Songbirds & Snakes',
                'mo_ta' => 'Nguồn gốc của Tổng thống Snow thời trẻ.',
                'dao_dien' => 'Francis Lawrence',
                'dien_vien' => 'Tom Blyth, Rachel Zegler',
                'thoi_luong' => 157,
                'nam_san_xuat' => 2023,
                'quoc_gia' => 'USA',
                'movie_url' => 'hgbs.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=fuYtKqz0qP4',
                'trang_thai' => 1,
                'trang_thai_chieu' => 0,
                'ngay_tao' => '2024-12-15 08:30:00',
                'ngay_khoi_chieu' => '2025-02-05',
            ],
            [
                'id' => 31,
                'ten_phim' => 'Shazam! Fury of the Gods',
                'mo_ta' => 'Shazam và gia đình đối đầu các nữ thần Hy Lạp.',
                'dao_dien' => 'David F. Sandberg',
                'dien_vien' => 'Zachary Levi',
                'thoi_luong' => 130,
                'nam_san_xuat' => 2023,
                'quoc_gia' => 'USA',
                'movie_url' => 'shazam2.mp4',
                'poster_url' => 'https://www.studyphim.vn/system/movies/9233/thumbnails/original/Shazam_-Fury-of-the-Gods-_2023_.jpeg',
                'trailer_url' => 'https://www.youtube.com/watch?v=AIc671o9yCI',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-10-02 17:15:00',
                'ngay_khoi_chieu' => '2024-10-18',
            ],
            [
                'id' => 32,
                'ten_phim' => 'Ant-Man and the Wasp: Quantumania',
                'mo_ta' => 'Ant-Man đối đầu Kang trong thế giới lượng tử.',
                'dao_dien' => 'Peyton Reed',
                'dien_vien' => 'Paul Rudd, Evangeline Lilly',
                'thoi_luong' => 125,
                'nam_san_xuat' => 2023,
                'quoc_gia' => 'USA',
                'movie_url' => 'antman3.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=5WfTEZJnv_8',
                'trang_thai' => 1,
                'trang_thai_chieu' => 0,
                'ngay_tao' => '2024-12-18 13:55:00',
                'ngay_khoi_chieu' => '2025-02-12',
            ],
            [
                'id' => 33,
                'ten_phim' => 'Creed III',
                'mo_ta' => 'Adonis Creed đối mặt bạn cũ trong trận chiến lớn nhất.',
                'dao_dien' => 'Michael B. Jordan',
                'dien_vien' => 'Michael B. Jordan, Jonathan Majors',
                'thoi_luong' => 116,
                'nam_san_xuat' => 2023,
                'quoc_gia' => 'USA',
                'movie_url' => 'creed3.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=AHmCH7iB_IM',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-09-28 14:40:00',
                'ngay_khoi_chieu' => '2024-10-12',
            ],
            [
                'id' => 34,
                'ten_phim' => 'Top Gun: Maverick',
                'mo_ta' => 'Phi công Maverick huấn luyện thế hệ mới.',
                'dao_dien' => 'Joseph Kosinski',
                'dien_vien' => 'Tom Cruise, Miles Teller',
                'thoi_luong' => 131,
                'nam_san_xuat' => 2022,
                'quoc_gia' => 'USA',
                'movie_url' => 'topgun2.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=giXco2jaZ_4',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-10-15 10:25:00',
                'ngay_khoi_chieu' => '2024-10-30',
            ],
            [
                'id' => 35,
                'ten_phim' => 'Jumanji: The Next Level',
                'mo_ta' => 'Nhóm bạn quay lại Jumanji để cứu Spencer.',
                'dao_dien' => 'Jake Kasdan',
                'dien_vien' => 'Dwayne Johnson, Kevin Hart',
                'thoi_luong' => 123,
                'nam_san_xuat' => 2019,
                'quoc_gia' => 'USA',
                'movie_url' => 'jumanji.mp4',
                'poster_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXif1wvmt0jYZkXe4jIQQhB_sgBm6ZWZtftQ&s',
                'trailer_url' => 'https://www.youtube.com/watch?v=rBxcF-r9Ibs',
                'trang_thai' => 1,
                'trang_thai_chieu' => 0,
                'ngay_tao' => '2024-12-20 15:10:00',
                'ngay_khoi_chieu' => '2025-02-20',
            ],
            [
                'id' => 36,
                'ten_phim' => 'Mulan (Live Action)',
                'mo_ta' => 'Mộc Lan cải trang thành nam để nhập ngũ bảo vệ gia đình.',
                'dao_dien' => 'Niki Caro',
                'dien_vien' => 'Liu Yifei, Donnie Yen',
                'thoi_luong' => 115,
                'nam_san_xuat' => 2020,
                'quoc_gia' => 'USA',
                'movie_url' => 'mulan.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=KK8FHdFluOQ',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-11-01 09:50:00',
                'ngay_khoi_chieu' => '2024-11-18',
            ],
            [
                'id' => 37,
                'ten_phim' => 'The Conjuring 3',
                'mo_ta' => 'Warren điều tra vụ án giết người liên quan đến ác quỷ.',
                'dao_dien' => 'Michael Chaves',
                'dien_vien' => 'Patrick Wilson, Vera Farmiga',
                'thoi_luong' => 112,
                'nam_san_xuat' => 2021,
                'quoc_gia' => 'USA',
                'movie_url' => 'conjuring3.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/xbSuFiJbbBWCkyCCKIMfuDCA4yV.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=h9Q4zZS2v1k',
                'trang_thai' => 1,
                'trang_thai_chieu' => 0,
                'ngay_tao' => '2024-12-25 11:25:00',
                'ngay_khoi_chieu' => '2025-02-28',
            ],
            [
                'id' => 38,
                'ten_phim' => 'A Quiet Place Part II',
                'mo_ta' => 'Gia đình Abbott tiếp tục sinh tồn trước sinh vật săn âm thanh.',
                'dao_dien' => 'John Krasinski',
                'dien_vien' => 'Emily Blunt, Cillian Murphy',
                'thoi_luong' => 97,
                'nam_san_xuat' => 2020,
                'quoc_gia' => 'USA',
                'movie_url' => 'quietplace2.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/4q2hz2m8hubgvijz8Ez0T2Os2Yv.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=BpdDN9d9Jio',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-10-22 16:30:00',
                'ngay_khoi_chieu' => '2024-11-05',
            ],
            [
                'id' => 39,
                'ten_phim' => 'Knives Out',
                'mo_ta' => 'Thám tử Benoit Blanc điều tra vụ giết người bí ẩn.',
                'dao_dien' => 'Rian Johnson',
                'dien_vien' => 'Daniel Craig, Ana de Armas',
                'thoi_luong' => 131,
                'nam_san_xuat' => 2019,
                'quoc_gia' => 'USA',
                'movie_url' => 'knivesout.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=qGqiHJTsRkQ',
                'trang_thai' => 1,
                'trang_thai_chieu' => 0,
                'ngay_tao' => '2024-12-28 14:05:00',
                'ngay_khoi_chieu' => '2025-03-05',
            ],
            [
                'id' => 40,
                'ten_phim' => 'The Revenant',
                'mo_ta' => 'Hugh Glass sống sót kỳ diệu để trả thù.',
                'dao_dien' => 'Alejandro G. Iñárritu',
                'dien_vien' => 'Leonardo DiCaprio, Tom Hardy',
                'thoi_luong' => 156,
                'nam_san_xuat' => 2015,
                'quoc_gia' => 'USA',
                'movie_url' => 'revenant.mp4',
                'poster_url' => 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/ji3ecJphATlVgWNY0B0RVXZizdf.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=LoebZZ8K5N0',
                'trang_thai' => 1,
                'trang_thai_chieu' => 1,
                'ngay_tao' => '2024-10-28 13:40:00',
                'ngay_khoi_chieu' => '2024-11-12',
            ],
        ]);
    }
}
